### ISSUE TITLE
ScrapliConnectionNotOpened error for address family AF_INET

### ISSUE THREAD

**Issue by Kani999** [scrapli/nornir_scrapli#59]
Hello again,

Today I've run into another problem:

```
Result:
Traceback (most recent call last):
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/scrapli/transport/base/base_socket.py", line 81, in _connect
    self.sock.connect((self.host, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 38, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 167, in open
    connection.open()
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/scrapli_netconf/driver/sync_driver.py", line 115, in open
    self.transport.open_netconf()
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/scrapli_netconf/transport/plugins/ssh2/transport.py", line 26, in open_netconf
    super().open()
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/scrapli/transport/plugins/ssh2/transport.py", line 52, in open
    self.socket.open()
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/scrapli/transport/base/base_socket.py", line 133, in open
    self._connect(socket_address_families=socket_address_families)
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/scrapli/transport/base/base_socket.py", line 89, in _connect
    raise ScrapliConnectionNotOpened(msg) from exc
scrapli.exceptions.ScrapliConnectionNotOpened: connection refused trying to open socket to 10.10.10.30 on port 830for address family AF_INET
```

It happens for the IOSXR devices: (NCS 540, XR 9000v) 
---

my configuration (groups):

```
IOSXR:
  platform: iosxr
  connection_options:
    scrapli_netconf:
      port: 830
      strip_namespaces: True
      extras:
        transport: ssh2
        ssh_config_file: False
        auth_strict_key: False
```

---
`iosxe` devices with same configuration works. 

---
`scrapli.log`

```
ID    | TIMESTAMP               | LEVEL    | (UID:)HOST:PORT           | MESSAGE
1     | 2021-07-13 15:02:33,813 | DEBUG    | 10.22.40.3:830            | setting 'server_capabilities' value to '[]'
2     | 2021-07-13 15:02:33,813 | INFO     | 10.22.40.3:830            | opening connection to '10.22.40.3' on port '830'
3     | 2021-07-13 15:02:33,813 | DEBUG    | 10.22.40.3:830            | opening transport connection to '10.22.40.3' on port '830'
4     | 2021-07-13 15:02:33,813 | DEBUG    | 10.22.40.3:830            | opening socket connection to '10.22.40.3' on port '830'
5     | 2021-07-13 15:02:33,833 | WARNING  | 10.22.40.3:830            | connection refused trying to open socket to 10.22.40.3 on port 830for address family AF_INET
```

---
`nornir.log`

```
2021-07-13 15:02:33,800 -  nornir.core -     INFO -        run() - Running task 'install_acl' with args {'dry_run': True} on 1 hosts
2021-07-13 15:02:33,800 - nornir.core.task -    DEBUG -      start() - Host 'XR9000v': running task 'install_acl'
2021-07-13 15:02:33,806 -  nornir.core -     INFO -        run() - Running task 'netconf_edit_config' with args {'diff': True, 'config': '  <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">\n   <ipv4-acl-and-prefix-list xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-acl-cfg">\n    <accesses>\n     <access xc:operation="replace">\n      <access-list-name>pristup_vty_nornir</access-list-name>\n      <access-list-entries>\n       <access-list-entry>\n        <sequence-number>10</sequence-number>\n        <sequence-str>10</sequence-str>\n        <remark>MGMT segment - Zarovka/Athena/Hermes/Saint</remark>\n       </access-list-entry>\n       <access-list-entry>\n        <sequence-number>20</sequence-number>\n        <sequence-str>20</sequence-str>\n        <grant>permit</grant>\n        <source-network>\n         <source-address>1.2.3.4</source-address>\n         <source-wild-card-bits>0.0.0.15</source-wild-card-bits>\n        </source-network>\n       </access-list-entry>\n       <access-list-entry>\n        <sequence-number>30</sequence-number>\n        <sequence-str>30</sequence-str>\n        <grant>permit</grant>\n        <source-network>\n         <source-address>195.178.64.160</source-address>\n         <source-wild-card-bits>0.0.0.15</source-wild-card-bits>\n        </source-network>\n       </access-list-entry>\n      </access-list-entries>\n     </access>\n    </accesses>\n   </ipv4-acl-and-prefix-list>\n </config>', 'dry_run': True, 'target': 'candidate'} on 1 hosts
2021-07-13 15:02:33,806 - nornir.core.task -    DEBUG -      start() - Host 'XR9000v': running task 'netconf_edit_config'
2021-07-13 15:02:33,834 - nornir.core.task -    ERROR -      start() - Host 'XR9000v': task 'netconf_edit_config' failed with traceback:
Traceback (most recent call last):
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/scrapli/transport/base/base_socket.py", line 81, in _connect
    self.sock.connect((self.host, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 38, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 167, in open
    connection.open()
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/scrapli_netconf/driver/sync_driver.py", line 115, in open
    self.transport.open_netconf()
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/scrapli_netconf/transport/plugins/ssh2/transport.py", line 26, in open_netconf
    super().open()
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/scrapli/transport/plugins/ssh2/transport.py", line 52, in open
    self.socket.open()
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/scrapli/transport/base/base_socket.py", line 133, in open
    self._connect(socket_address_families=socket_address_families)
  File "/home/jankrupa/networksys_lab/nornir_networksys_lab/venv/lib/python3.8/site-packages/scrapli/transport/base/base_socket.py", line 89, in _connect
    raise ScrapliConnectionNotOpened(msg) from exc
scrapli.exceptions.ScrapliConnectionNotOpened: connection refused trying to open socket to 10.20.30.40 on port 830for address family AF_INET

2021-07-13 15:02:33,835 -  nornir.core -     INFO -        run() - Running task 'Discarding changes' with args {} on 1 hosts
```

---
- versions
``` 
pip list | grep scrapli
nornir-scrapli        2021.1.30  
scrapli               2021.7.30a3
scrapli-community     2021.1.30  
scrapli-netconf       2021.1.30  
```

---

- Do you have any idea what's wrong?

**Comment by carlmontanari** [comment]
Hey @Kani999 👋 

That exception is really just wrapping the low level socket library `ConnectionRefusedError` -- so we are getting that message from the `sock.connect` itself (actual tcp socket happening before even ssh2-python bits happen). 

Does this error happen every time or just intermittently? Does it work w/ `system` or `paramiko` transports? The most obvious answer is just that the device is not listening on 830, is it possible the device doesn't have netconf enabled or there is something else like that going on? Failing that, trying the other transports is the only obvious thing I can think of off the top of my head.

If you want to take a peak at this section fo code you can find it [here](https://github.com/carlmontanari/scrapli/blob/master/scrapli/transport/base/base_socket.py#L80-L89).

Carl

**Comment by Kani999** [comment]
@carlmontanari 
Hello, the error is really in the port settings for netconf. I got the wrong lab specification of network devices. Each device has a different port opened for Netconf.
I apologize for the open ticket and thank you for the analysis.
