### ISSUE TITLE
Issue on Juniper EX Models JunOS version 17.3R3-S4.2

### ISSUE THREAD

**Issue by gcasella** [scrapli/nornir_scrapli#68]
**Describe the bug**
Hey!
First I wanted to say I love what you're doing with scrapli!

The issue that I'm experiencing is that when I attempt to use scrapli_netconf with Nornir I'm unable to establish a proper netconf connection to a device when it is using port 830. 
If I modify my groups.yaml file to use port 22 instead, everything works as expected.

This happens with using either the _**system**_ or _**ssh2**_ transport methods.
You can see more details below.

**To Reproduce**
**hosts.yaml**
```
---
rtr01:
   hostname: 10.0.0.1
   groups:
     - juniper
   data:
      type: network_device
rtr02:
   hostname: 10.0.0.2
   groups:
     - juniper
   data:
      type: network_device
rtr03:
   hostname: 10.0.0.3
   groups:
     - juniper
   data:
      type: network_device
```

**groups.yaml**
```
---
network_devices: {}

juniper:
  platform: junos
  connection_options:
    scrapli_netconf:
      port: 830
      extras:
        transport: ssh2
        timeout_socket: 5
        ssh_config_file: False
        auth_strict_key: False
```

**pull_config_netconf.py**
```
import logging
from jnpr.junos import exception
from nornir import InitNornir
from nornir.core.filter import F
from nornir_utils.plugins.functions import print_result
from config import nornir, nornir_username, nornir_password
from scrapli.logging import enable_basic_logging

enable_basic_logging(file=True, level="debug")
from nornir_scrapli.tasks import (
    netconf_capabilities,
    netconf_edit_config,
    netconf_get,
    netconf_get_config,
    netconf_lock,
    netconf_rpc,
    netconf_unlock,
)


nr = InitNornir(**nornir)
nr.inventory.defaults.username = "admin"
nr.inventory.defaults.password = "admin"


inv_filter = nr.filter(F(groups__contains='juniper'))

snmp_config = inv_filter.run(
    task=netconf_get_config,
)
print_result(snmp_config)
```

**Stack Trace**
```
vvvv netconf_get_config ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.8/dist-packages/nornir_scrapli/tasks/netconf/get_config.py", line 31, in netconf_get_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/usr/local/lib/python3.8/dist-packages/nornir_scrapli/connection.py", line 280, in open
    connection.open()
  File "/usr/local/lib/python3.8/dist-packages/scrapli_netconf/driver/sync_driver.py", line 115, in open
    self.transport.open_netconf()
  File "/usr/local/lib/python3.8/dist-packages/scrapli_netconf/transport/plugins/ssh2/transport.py", line 26, in open_netconf
    super().open()
  File "/usr/local/lib/python3.8/dist-packages/scrapli/transport/plugins/ssh2/transport.py", line 74, in open
    self._open_channel()
  File "/usr/local/lib/python3.8/dist-packages/scrapli_netconf/transport/plugins/ssh2/transport.py", line 50, in _open_channel
    self.session_channel.pty()
  File "ssh2/channel.pyx", line 60, in ssh2.channel.Channel.pty
  File "ssh2/utils.pyx", line 174, in ssh2.utils.handle_error_codes
ssh2.exceptions.ChannelRequestDenied
```

If i change the port to port 22 I will get this output instead;
```
vvvv netconf_get_config ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv INFO
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/17.3R3/junos" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101">
  <data>
    <configuration xmlns="http://xml.juniper.net/xnm/1.1/xnm" junos:commit-seconds="1627573369" junos:commit-localtime="2021-07-29 15:42:49 UTC" junos:commit-user="phdeshai">
      <version>17.3R3-S4.2</version>
      <system>
...output omitted...
```

**OS (please complete the following information):**
 - OS: Ubuntu
```
nornir-scrapli==2021.7.30
scrapli==2021.7.30
scrapli-cfg==2021.7.30
scrapli-community==2021.7.30
scrapli-netconf==2021.7.30
scrapli-ssh2==2020.10.24
```

**Comment by carlmontanari** [comment]
Hey @gcasella 

It *sounds* like the device is just not listening for netconf on 830. IIRC junos defaults to 22 for netconf (but I am the last person to ask about junos things 😁 ). You can test it manually like:

```
ssh -l your username -p 830 yourhost -s netconf
```

if that works (you get logged in/dont get connection refused) then scrapli *should* work... but given that ssh2 is complaining about channel getting denied I think that its probably the device not listening on that port... let us know!

Carl

**Comment by gcasella** [comment]
Hey @carlmontanari ,
The device is definitely listening on port 830. I run different automation towards the device using Netconf and it uses port 830.

For example, using nornir_pyez will work just fine using port 830 towards this device, even just raw ncclient.

For completion on what you asked for I'll post the results of the command you gave me.

**Comment by gcasella** [comment]
@carlmontanari here's the response;
```
<!-- No zombies were killed during the creation of this user interface -->
<!-- user readwrite, class j-readwrite -->
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file</capability>
    <capability>urn:ietf:params:xml:ns:netconf:base:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:url:1.0?protocol=http,ftp,file</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring</capability>
    <capability>http://xml.juniper.net/netconf/junos/1.0</capability>
    <capability>http://xml.juniper.net/dmi/system/1.0</capability>
  </capabilities>
  <session-id>84471</session-id>
</hello>
```

Also, here's an nmap
```
Nmap scan report for 10.117.225.125
Host is up (0.013s latency).

PORT    STATE SERVICE
830/tcp open  netconf-ssh

Nmap done: 1 IP address (1 host up) scanned in 0.15 seconds
```

**Comment by gcasella** [comment]
Here is the output when leaving the transport as it's default in the **groups.yaml** file;

```
vvvv netconf_get_config ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/scrapli/transport/plugins/system/ptyprocess.py", line 427, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/scrapli/transport/plugins/system/transport.py", line 126, in read
    buf = self.session.read(65535)
  File "/usr/local/lib/python3.8/dist-packages/scrapli/transport/plugins/system/ptyprocess.py", line 432, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.8/dist-packages/nornir_scrapli/tasks/netconf/get_config.py", line 31, in netconf_get_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/usr/local/lib/python3.8/dist-packages/nornir_scrapli/connection.py", line 280, in open
    connection.open()
  File "/usr/local/lib/python3.8/dist-packages/scrapli_netconf/driver/sync_driver.py", line 121, in open
    self.channel.channel_authenticate_netconf(
  File "/usr/local/lib/python3.8/dist-packages/scrapli/decorators.py", line 276, in decorate
    return self._multiprocessing_timeout(
  File "/usr/local/lib/python3.8/dist-packages/scrapli/decorators.py", line 337, in _multiprocessing_timeout
    return future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/scrapli_netconf/channel/sync_channel.py", line 100, in channel_authenticate_netconf
    buf = self.read()
  File "/usr/local/lib/python3.8/dist-packages/scrapli/channel/sync_channel.py", line 69, in read
    buf = self.transport.read()
  File "/usr/local/lib/python3.8/dist-packages/scrapli/decorators.py", line 95, in decorate
    return self._multiprocessing_timeout(
  File "/usr/local/lib/python3.8/dist-packages/scrapli/decorators.py", line 173, in _multiprocessing_timeout
    return future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/scrapli/transport/plugins/system/transport.py", line 133, in read
    raise ScrapliConnectionError(msg) from exc
scrapli.exceptions.ScrapliConnectionError: encountered EOF reading from transport; typically means the device closed the connection

^^^^ END netconf_get_config ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by carlmontanari** [comment]
Looks sorta like [this](https://kb.juniper.net/InfoCenter/index?page=content&id=KB35209&cat=QFX_SERIES&actp=LIST) but also more/worse than that.....

All transports force a pty (psuedoterminal) and apparently junos just refuses to allocate one on a port that isn't port 22. You can manually remove the `-tt` from system transport `open_cmd` prior to a connection being opened which will no longer force the ptpy but thats kinda a pita in context of nornir (I *think* doable though). You could also patch the open method of ssh2/paramiko to not force the pty, but again a pita, and isn't a "fix" really, at least in my mind. 

For the time being I think I am going to stuff this in the "not broke, wont fix" bucket since I am against making changes to "core" things for the sake of a single platform. I'll sleep on it a bit though.

**Comment by gcasella** [comment]
@carlmontanari thanks for the response.

I know about that type of issue already. The one other thing I wanted to share was a bit of the logs that we would see on my Juniper itself;


**Using system transport**
```
Aug 10 21:37:07  rtr01 sshd[84589]: Accepted keyboard-interactive/pam for admin from 192.168.1.21 port 36308 ssh2
```

**Using ssh2 transport**
```
Aug 10 21:37:43  rtr01 sshd[84599]: Accepted password for admin from 192.168.1.21 port 36366 ssh2
```

I removed the `-tt` from the source config for `scrapli_netconf/transport/plugins/system/transport.py` on line 27 and then my connection was successful using port 830, now i'm sure this is only related towards Juniper Devices, using other applications like Ansible or NAPALM would utilize Juniper's PyEz Python Library for netconf connections.

**Comment by gcasella** [comment]
I was wondering, could it be an optional attribute to the connection? For example `use_tty` with the value `True` as the default? Similar to how ansible has implemented it?

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/ssh_connection.html

**Comment by carlmontanari** [comment]
Yeah its a possibility. I kinda hate having it as a flag since its super low level and I think most users wouldn't know if they needed it or not -- and even adding a warning/message in an exception could be misleading (since the same exception is raised for "genuine" connection issues). 

All that said... this weekend or next weekend at the latest I will test things out a bit more and let ya know what I decide. In the meantime if you are keen to working up a PR I'd be happy to review and may give me a jumpstart on getting things tested/rolling. (If you do, please use develop branch!)

Thanks again for opening this and the testing/details, its appreciated!

Carl

**Comment by carlmontanari** [comment]
Hey @gcasella 

Spent some time on this today... if you would like to test things you can install scrapli-netconf `flag_to_disable_pty` branch like:

```
pip install -e git+https://github.com/scrapli/scrapli_netconf.git@flag_to_disable_pty#egg=scrapli_netconf
```

Spent some time looking at asyncssh and why/how it always works (tl;dr it is awesome and Ron is awesome) -- turns out that asyncssh *never* requests a pty when using a subsystem. So thats cool/easy - I can just remove the pty from ssh2/paramiko. That alone solves your problem (as we already know!) if you want to use those transports.

System transport is a bit different of a beast though because we are doing subprocess magic basically. Removing the `-t` bits does make things work, however there are some other complications there it seems (unrelated to this issue -- was nxos and really really big payload related). So... long story short I did *not* remove the pty forcing bits for system transport. What I *did* do is add a `transport_option` that allows you to control it. I didn't want to add a "global" option that didn't apply to the other transports so this is I think a decent compromise.

```
DEVICE = {
    "host": "localhost",
    "auth_username": "boxen",
    "auth_password": "b0x3N-b0x3N",
    "auth_strict_key": False,
    "port": 25830,
    "transport": "system",
    "transport_options": {"netconf_force_pty": False}
}

conn = NetconfDriver(**DEVICE)
conn.open()
result = conn.get_config(source="running")
```

The above bits works nicely w/ my vsrx. If I set the `netconf_force_pty` to `True` we are back to the original behavior that spawned this issue. So... I think this should work! If you have some time and can test and let us know if this resolves things (with all the transports) that would be much appreciated!

Thanks again for the help on this!

Carl

**Comment by gcasella** [comment]
Hey @carlmontanari Thanks for this!
Just running some tests now;

I see SSH2 you removed the pty, i do get this now when i attempt to pull the full config (I'm not applying any filters);

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.8/dist-packages/nornir_scrapli/tasks/netconf/get_config.py", line 32, in netconf_get_config
    scrapli_response = scrapli_conn.get_config(
TypeError: get_config() got an unexpected keyword argument 'filters'

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.8/dist-packages/nornir_scrapli/tasks/netconf/get_config.py", line 32, in netconf_get_config
    scrapli_response = scrapli_conn.get_config(
TypeError: get_config() got an unexpected keyword argument 'filters'

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.8/dist-packages/nornir_scrapli/tasks/netconf/get_config.py", line 32, in netconf_get_config
    scrapli_response = scrapli_conn.get_config(
TypeError: get_config() got an unexpected keyword argument 'filters'
```

Config being run;
```
inv_filter.run(
        task=netconf_get_config,
    )
```


---------------

Using System i got the same error as above.

-----
I've never tried the asyncssh before but when i tried i got this;
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.8/dist-packages/nornir_scrapli/tasks/netconf/get_config.py", line 31, in netconf_get_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/usr/local/lib/python3.8/dist-packages/nornir_scrapli/connection.py", line 279, in open
    connection = NetconfDriver(**parameters)
  File "/root/prefect/snmp_config/src/scrapli-netconf/scrapli_netconf/driver/sync_driver.py", line 48, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/scrapli/driver/base/sync_driver.py", line 16, in __init__
    raise ScrapliValueError(
scrapli.exceptions.ScrapliValueError: provided transport is *not* an sync transport, must use an sync transport with the (sync)Driver(s)

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.8/dist-packages/nornir_scrapli/tasks/netconf/get_config.py", line 31, in netconf_get_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/usr/local/lib/python3.8/dist-packages/nornir_scrapli/connection.py", line 279, in open
    connection = NetconfDriver(**parameters)
  File "/root/prefect/snmp_config/src/scrapli-netconf/scrapli_netconf/driver/sync_driver.py", line 48, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/scrapli/driver/base/sync_driver.py", line 16, in __init__
    raise ScrapliValueError(
scrapli.exceptions.ScrapliValueError: provided transport is *not* an sync transport, must use an sync transport with the (sync)Driver(s)

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.8/dist-packages/nornir_scrapli/tasks/netconf/get_config.py", line 31, in netconf_get_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/usr/local/lib/python3.8/dist-packages/nornir_scrapli/connection.py", line 279, in open
    connection = NetconfDriver(**parameters)
  File "/root/prefect/snmp_config/src/scrapli-netconf/scrapli_netconf/driver/sync_driver.py", line 48, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/scrapli/driver/base/sync_driver.py", line 16, in __init__
    raise ScrapliValueError(
scrapli.exceptions.ScrapliValueError: provided transport is *not* an sync transport, must use an sync transport with the (sync)Driver(s)
```

**Comment by carlmontanari** [comment]
Ugh... I really need to just auto generate nornir scrapli to keep it up to date... I dont use nornir for anything so stuff like this tends to happen... that `filters` arg got deprecated (or rather renamed -> `filter_` for consistency w/ the other methods) in scrapli-netconf but clearly I missed updating it here. 

I'll fix this and release a post version of nornir-scrapli to fix this. In the meantime you can just use scrapli netconf directly to test if you have time:

```
from scrapli_netconf import NetconfDriver

DEVICE = {
    "host": "localhost",
    "auth_username": "boxen",
    "auth_password": "b0x3N-b0x3N",
    "auth_strict_key": False,
    "port": 25830,
    "transport": "system",
}

conn = NetconfDriver(**DEVICE)
conn.open()
result = conn.get_config()
print(result.result)
```

The async bits will not work in nornir-scrapli anyway so you can ignore that. If you did want to try it out w/out nornir you can do it like:

```
import asyncio

from scrapli_netconf.driver import AsyncNetconfDriver

DEVICE = {
    "host": "localhost",
    "auth_username": "boxen",
    "auth_password": "b0x3N-b0x3N",
    "auth_strict_key": False,
    "transport": "asyncssh",
    "port": 25830
}


async def main():
    conn = AsyncNetconfDriver(** DEVICE)
    await conn.open()
    result = await conn.get_config()
    print(result.result)


if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())
```

**Comment by gcasella** [comment]
Hey @carlmontanari all works as expected.
SSH2 / system / asyncssh work as expected with the changes you had made!

**Comment by carlmontanari** [comment]
@gcasella thank you so much for confirming! I will merge the scrapli-netconf branch sometime this week as well as release a pre-release (2022.01.30a1) of nornir-scrapli. I'll update this thread when thats done!

Carl

**Comment by carlmontanari** [comment]
@gcasella thanks again for the help with this. I've pushed out pre-release versions of scrapli-netconf and nornir-scrapli (2022.01.30a1 for both), so we should be good to go if you pin to those! I'll close this for now since I think we are sorted out here, but feel free to re-open if I missed anything!

Thanks again!

Carl
