### ISSUE TITLE
Host key verification failed for host {hostname}

### ISSUE THREAD

**Issue by jblokesh** [scrapli/nornir_scrapli#69]
Simple script as below, but I get error Host key verification failed for host {hostname}
Running from Linux machine, but I am able to SSH directly to host.

"""
from nornir import InitNornir
from nornir_scrapli.tasks import netconf_edit_config, netconf_commit
from nornir_utils.plugins.functions import print_result
from nornir_jinja2.plugins.tasks import template_file

nr = InitNornir(config_file="config.yaml")

def srpolicycleanup(task):
    """
    This function is defined to cleanup the segment-routing traffic-eng config and then recreate minimum required config. Defined using Netconf method.
    """
    srtedelete = task.run(task=template_file, name="srpolicycleanup", template="sr-te-cleanup.j2", path="./templates")
    srtedelete_output = srtedelete.result
    task.run(task=netconf_edit_config, target="candidate", config=srtedelete_output)
    task.run(task=netconf_commit)

result = nr.run(task=srpolicycleanup)
print_result(result)
"""

**Comment by jblokesh** [comment]
Complete error log, could someone please help, what am I missing? how to solve this

Traceback (most recent call last):
  File "/home/jnyanesh/.local/lib/python3.6/site-packages/scrapli/transport/ptyprocess.py", line 395, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jnyanesh/.local/lib/python3.6/site-packages/scrapli_netconf/transport/systemssh.py", line 103, in _authenticate
    new_output = self.session.read()
  File "/home/jnyanesh/.local/lib/python3.6/site-packages/scrapli/transport/ptyprocess.py", line 400, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jnyanesh/.local/lib/python3.6/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/jnyanesh/.local/lib/python3.6/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 38, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/jnyanesh/.local/lib/python3.6/site-packages/nornir/core/inventory.py", line 448, in get_connection
    extras=conn.extras,
  File "/home/jnyanesh/.local/lib/python3.6/site-packages/nornir/core/inventory.py", line 499, in open_connection
    configuration=configuration,
  File "/home/jnyanesh/.local/lib/python3.6/site-packages/nornir_scrapli/connection.py", line 166, in open
    connection.open()
  File "/home/jnyanesh/.local/lib/python3.6/site-packages/scrapli_netconf/driver/driver.py", line 64, in open
    login_bytes = self.transport.open_netconf()
  File "/home/jnyanesh/.local/lib/python3.6/site-packages/scrapli_netconf/transport/systemssh.py", line 38, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/jnyanesh/.local/lib/python3.6/site-packages/scrapli_netconf/transport/systemssh.py", line 58, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/jnyanesh/.local/lib/python3.6/site-packages/scrapli/decorators.py", line 114, in decorate
    wrapped_func=wrapped_func, args=args, kwargs=kwargs
  File "/home/jnyanesh/.local/lib/python3.6/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/jnyanesh/.local/lib/python3.6/site-packages/scrapli_netconf/transport/systemssh.py", line 107, in _authenticate
    self._ssh_message_handler(output=output)
  File "/home/jnyanesh/.local/lib/python3.6/site-packages/scrapli/transport/systemssh.py", line 286, in _ssh_message_handler
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: Host key verification failed for host 10.91.126.111

**Comment by jblokesh** [comment]
Host info just in case:

ar1:
  hostname: 10.91.126.111
  data:
    connection_options: 
      scrapli:
        platform: cisco_iosxr
        port: 22
        extras:
          ssh_config_file: True
          auth_strict_key: False
      scrapli_netconf:
        port: 830
        extras:
          ssh_config_file: True
          auth_strict_key: False

**Comment by carlmontanari** [comment]
Please please please format your posts in the future! Looks like ya tried, but it should be three "back ticks" (under the escape key, top-left on US keyboards at least) not quotes.

The connection options stuff in your inventory should not be under `data` - data is for arbitrary user variables and stuff. [Here](https://github.com/scrapli/nornir_scrapli/blob/master/examples/structured_data/nornir_data/groups.yaml) is an example of a good inventory.

Going to close this as it isn't a bug/feature request. Please use github discussions/slack/discord for non-bug type things. I'm hoping to try to keep issues sparse and just focused on bugs/new features. Thanks!

Carl
