### ISSUE TITLE
replace config problem

### ISSUE THREAD

**Issue by denisvorlov** [scrapli/nornir_scrapli#83]
Hi, I'm using nornir_scrapli plugin
When using 
```
task.run(
      task=napalm_configure,
      dry_run=True,
      filename=config,
      replace=True,
  )
```
I'm getting the following error.
```
nornir.core.task -    ERROR -      start() - Host 'sw01-stack-floor2': task 'replace_config' failed with traceback:
Traceback (most recent call last):
  File "/home/venv/myenv/lib64/python3.6/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/python/project/main.py", line 172, in replace_config
    severity_level=logging.DEBUG
  File "/home/venv/myenv/lib64/python3.6/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)
```
I must to note, that I faced with such behavior for the first time. Many devices, that I'm dealing with have no such error and everything works as expected.
Can you help, please to understand the cause of this and how it can be fixed?

**Comment by carlmontanari** [comment]
Your code/exception is not for the nornir scrapli plugin, so no can’t help you.
